<a href="https://colab.research.google.com/github/Ercampa2/Aulas_Inteligencia_Artificial/blob/main/tictactoeCalculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import time

In [26]:
def evaluate_board(board, player):
  count = 0

  if(player == 1):
    enemy = 2
  else:
    enemy = 1

  for x in board:
    if enemy not in board[x]:
      count += 1

  for y in range(3):
    if enemy not in board[:,y]:
      count += 1

  if enemy in [board[0,0],board[1,1],board[2,2]]:
    count += 1

  if enemy in [board[0,2],board[1,1],board[2,0]]:
    count += 1

  return count

  
  


In [3]:
def random_board():
  return np.random.randint(3, size=(3,3))

In [10]:
board = random_board()

print(evaluate_board(board,1))

--
[2 0 1]
--
[1 2 1]
--
[0 1 0]
None


In [31]:
def board_evaluator(board, max_timer):
  count = 0
  elapsed_time = 0
  start_timer = time.time()
  while elapsed_time < max_timer:
    eval = evaluate_board(board, 1)
    count += 1
    elapsed_time = time.time() - start_timer

  return count

  

In [30]:
board = random_board()
board_evaluator(board, 2)

53646