<a href="https://colab.research.google.com/github/Ercampa2/Aulas_Inteligencia_Artificial/blob/main/tictactoeCalculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [14]:
def evaluate_board(board, player):
  count = 0

  if(player == 1):
    enemy = 2
  else:
    enemy = 1

  for x in board:
    if enemy not in board[x]:
      count += 1

  for y in range(len(board)):
    print(board[:,y])
    if enemy not in board[:,y]:
      count += 1

  

  
  


In [12]:
def random_board():
  return np.random.randint(3, size=(3,3))

In [15]:
board = random_board()
print(board)
evaluate_board(board,1)

[[2 1 2]
 [0 2 0]
 [0 2 2]]
[2 0 0]
[1 2 2]
[2 0 2]
